### ISSUE TITLE
Error when try to inference

### ISSUE THREAD

**Issue by JuntingGuo** [GanjinZero/RRHF#12]
Traceback (most recent call last):
  File "single_sentence_inference.py", line 7, in <module>
    from stanford_alpaca.train import smart_tokenizer_and_embedding_resize, DEFAULT_PAD_TOKEN, DEFAULT_EOS_TOKEN, DEFAULT_BOS_TOKEN, DEFAULT_UNK_TOKEN
ModuleNotFoundError: No module named 'stanford_alpaca'

Seems like stanford_alpaca should be cloned into the directory .

**Comment by GanjinZero** [comment]
Fix it. Please check if it worked.

**Comment by JuntingGuo** [comment]
Thanks for the quick response and yes it worked.
Another thing, I suppose Chinese is not currently supported? Since I got this really weird response when try to get a Chinese answer.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/29737578/231992078-ee127750-a80d-43fd-a578-c40f1e1dae00.png">

**Comment by GanjinZero** [comment]
Wombat-7B is not trained by Chinese.
We will train a Wombat-7B-Chinese and release it later.

**Comment by JuntingGuo** [comment]
Got it. Thanks!
