### ISSUE TITLE
Wombat weights release?

### ISSUE THREAD

**Issue by artyemk** [GanjinZero/RRHF#3]
Any plans for weights release? Do you have a 7B model only?

**Comment by GanjinZero** [comment]
We have 7B only for now. We are researching how to release the weight correctly since Llama and alpaca does not provide their weights.

**Comment by artyemk** [comment]
You can release delta weights, like [FastChat](https://github.com/lm-sys/FastChat) did

**Comment by GanjinZero** [comment]
That is a really good idea. We will work on it.

**Comment by GanjinZero** [comment]
GanjinZero/wombat-7b-delta weight has been released!
